/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.soma;

/**
 *
 * @author caio.alunos
 */
public class FrmSoma extends javax.swing.JFrame {

    /**
     * Creates new form FrmSoma
     */
    public FrmSoma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblProjetoSoma = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblValor02 = new javax.swing.JLabel();
        lblValor01 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtValor02 = new javax.swing.JTextField();
        txtValor01 = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalcular.setBackground(new java.awt.Color(255, 51, 102));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 87, 40));

        btnLimpar.setBackground(new java.awt.Color(0, 255, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 88, 40));

        lblProjetoSoma.setText("Projeto Soma");
        getContentPane().add(lblProjetoSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 127, -1, -1));

        lblValor02.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 11)); // NOI18N
        lblValor02.setForeground(new java.awt.Color(255, 102, 0));
        lblValor02.setText("Valor 02:");
        getContentPane().add(lblValor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        lblValor01.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 11)); // NOI18N
        lblValor01.setForeground(new java.awt.Color(255, 102, 0));
        lblValor01.setText("Valor 01:");
        getContentPane().add(lblValor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblTotal.setFont(new java.awt.Font("Dubai", 0, 11)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 102, 0));
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        txtValor02.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        txtValor02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor02ActionPerformed(evt);
            }
        });
        getContentPane().add(txtValor02, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 166, -1));

        txtValor01.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().add(txtValor01, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 166, -1));

        txtTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 166, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // 1- Declara Variaveis

        double v1, v2, total;

        // passo -entrda
        v1 = Double.parseDouble(txtValor01.getText());
        v2 = Double.parseDouble(txtValor02.getText());

        // 3-passo processamento
        total = v1 + v2;

// 4 passo - saida
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:

        txtValor01.setText(null);
        txtValor02.setText(null);
        txtTotal.setText(null);


    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtValor02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSoma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSoma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblProjetoSoma;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValor01;
    private javax.swing.JLabel lblValor02;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtValor01;
    private javax.swing.JTextField txtValor02;
    // End of variables declaration//GEN-END:variables
}
